function model = build_reconstruction_model(params)
%BUILD_RECONSTRUCTION_MODEL Crea il modello numerico a partire dai parametri.

    model = define_model_for_reconstruction( ...
        params.field_of_view, ...
        params.number_of_grid_points_fov, ...
        params.device_probe_id, ...
        params.use_eir, ...
        params.use_indiv_eir, ...
        params.use_sir, ...
        params.use_single_speed_of_sound, ...
        params.speed_of_sound_tissue, ...
        params.num_cropped_samples_at_sinogram_start, ...
        params.filt_cutoff_min, ...
        params.filt_cutoff_max, ...
        params.model_normalization_factor);
end
