function [rec_img] = reconstruct_bp(model, K, sinogram, ProbeType)
% Perform backprojection reconstruction with the parameters that are specified in the provided model.

if ProbeType == "curved"
    rec_img = backproject_waveeq(...
        sinogram,...
        model.Discretization.region.xPositionsFov, ...
        model.Discretization.region.zPositionsFov,...
        model.Medium.speedOfSound, ...
        model.Probe.DAC.frequency,...
        model.DataPreprocessing.numCroppedSamplesAtSinogramStart + model.Probe.DAC.delayBeforeRecording,...
        model.Probe.detector.angularCoverage,...
        model.Probe.detector.radius,...
        1,...
        K);
else 
    rec_img = backproject_waveeq_linear_gpu(...
            sinogram,...
            model.Discretization.region.xPositionsFov, ...
            model.Discretization.region.zPositionsFov,...
            model.Probe.detector.xPositionsOfTransducers, ...
            model.Probe.detector.zPositionsOfTransducers,...
            model.Medium.speedOfSound, ...
            model.Probe.DAC.frequency,...
            model.DataPreprocessing.numCroppedSamplesAtSinogramStart + model.Probe.DAC.delayBeforeRecording,...
            1,...
            K);
end
rec_img = fliplr(rec_img);
disp("Flip fatto")
